### ISSUE TITLE
Spigot Mappings fail to load for 1.16.1

### ISSUE THREAD

**Issue by MattBDev** [MiniDigger/MiniMappingViewer#60]
When trying to load mappings for 1.16.1 the viewer fails to load the Spigot Mappings. I discovered that the gist file that is used to obtain the mappings for Spigot was out of date. I forked it and updated it with the correct links for the 1.16.1 Spigot mappings. Feel free to copy and paste it to update your gist file. https://gist.githubusercontent.com/MattBDev/1d5c1f2dcd14ba36829bce5525f9b7c5/raw/79b4467ee55c29454ef7e6ffc2e353b0bcd0c73f/builddata.json

**Comment by MiniDigger** [comment]
rip, didnt see your issue, I updated the gist myself. it wasnt the only issue anyways, needed to manually map the new main class.
thanks for bringing this up anyways!
