### ISSUE TITLE
Broken with 1.16.3

### ISSUE THREAD

**Issue by MattBDev** [MiniDigger/MiniMappingViewer#67]
Because mappings stayed the same between 1.16.2 and 1.16.3 the mapping viewer can't retrieve 1.16.3 mappings for Spigot causing an error.

**Comment by MiniDigger** [comment]
not broken, just not updated, fixed in https://github.com/MiniDigger/MiniMappingViewer/commit/9af7adc37fa10093eb1dddcade02cc83046a87d4
