### ISSUE TITLE
The viewer has stopped working completely

### ISSUE THREAD

**Issue by KaruzoHikari** [MiniDigger/MiniMappingViewer#90]
It looks like neither the Mojang -> Spigot, nor the Spigot -> Mojang viewers are working anymore?
Trying to check any of the versions results in a blank page:
![image](https://user-images.githubusercontent.com/35693714/112391187-d3040980-8cf7-11eb-9ce6-198b07d66048.png)

**Comment by MiniDigger** [comment]
temp fixed it for now
